name: shell commands

on: [push]

jobs:
  run-shell-command:
    runs-on: [ self-hosted ]
    steps:
      - name: what is our working environment
        run: |
          cat /etc/os-release
          uname -a 
          pwd
          ls -l 
          ls -l /
          docker --version
          
          
          



      
        
