name: shell commands

on: [push]

jobs:
  run-shell-command:
    runs-on: [ self-hosted ]
    steps:
      - name: what is our working environment
        run: |
          lsb_relase -a
          uname -a 
          pwd



      
        
