name: actions test

on: 
  push:

  workflow_dispatch:
  
  

  
jobs:
  pre-flight-checks:
    runs-on: [ self-hosted ]
    steps:
      - uses: actions/checkout@v2

          
  build-docker-image:
    runs-on: [self-hosted ]
    steps:
      - uses: actions/checkout@v2
      
      
      - name: what is our working environment
        run: |
          cat /etc/os-release
          uname -a 
          pwd
          ls -l 
          ls -l /
          docker --version
          
      - name: docker login
        run: |
          echo "${{ secrets.DOCKER_PUSH_TOKEN }}" | docker login mw-docker.repositories.mathworks.com -u "${{ secrets.DOCKER_PUSH_USER }}" --password-stdin
          docker info
          cat /home/runner/.docker/config.json

      - name: docker build
        run: |
          cd docker
          docker build . -t mw-docker.repositories.mathworks.com/gha-docker-push-sample-mallen:latest
          
      - name: step3
        run: |
          date
          pwd
          ls -l
          
