name: shell commands

on: [push]

jobs:
  run-shell-command:
    runs-on: [ self-hosted, runner-source=AWS ]
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiline script
        run: |
          date
          echo push test from ghe
          pwd



      
        
