name: shell commands

on: [push]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  
jobs:
  pre-flight-checks:
    runs-on: [ self-hosted ]
    steps:
      - name: what is our working environment
        run: |
          cat /etc/os-release
          uname -a 
          pwd
          ls -l 
          ls -l /
          docker --version
          
  build-docker-image:
    runs-on: [self-hosted ]
    steps:
      - name: docker login
        run: |
          echo "${{ secrets.DOCKER_PUSH_TOKEN }}" | docker login mw-docker.repositories.mathworks.com -u "${{ secrets.DOCKER_PUSH_USER }}" --password-stdin
          docker info
          cat /home/runner/.docker/config.json
          
      
        
 
